// <auto-generated />
using BSWeBtoon.Front.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BSWeBtoon.Front.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220619033157_AddDB")]
    partial class AddDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BSWeBtoon.Front.Models.Keydetail", b =>
                {
                    b.Property<string>("KeydetailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KeyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeydetailId");

                    b.ToTable("Keydetails");

                    b.HasData(
                        new
                        {
                            KeydetailId = "K001",
                            KeyName = "恐怖"
                        },
                        new
                        {
                            KeydetailId = "K002",
                            KeyName = "愛情"
                        },
                        new
                        {
                            KeydetailId = "K003",
                            KeyName = "親情"
                        },
                        new
                        {
                            KeydetailId = "K004",
                            KeyName = "BL"
                        });
                });

            modelBuilder.Entity("BSWeBtoon.Front.Models.WatchHistory", b =>
                {
                    b.Property<string>("WatchHistoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BgPic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComicPicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EpId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeoplePic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WatchHistoryId");

                    b.ToTable("WatchHistorys");

                    b.HasData(
                        new
                        {
                            WatchHistoryId = "W001",
                            BgPic = "https://www.niusnews.com/upload/imgs/default/2019MayJenny/24cute/1.jpg",
                            ComicId = "C001",
                            ComicPicId = "CP01",
                            EpId = "Ep01",
                            MemberId = "M001",
                            PeoplePic = "https://www.niusnews.com/upload/imgs/default/2019MayJenny/24cute/1.jpg"
                        },
                        new
                        {
                            WatchHistoryId = "W002",
                            BgPic = "https://www.niusnews.com/upload/imgs/default/2019MayJenny/24cute/1.jpg",
                            ComicId = "C002",
                            ComicPicId = "CP02",
                            EpId = "Ep02",
                            MemberId = "M002",
                            PeoplePic = "https://www.niusnews.com/upload/imgs/default/2019MayJenny/24cute/1.jpg"
                        },
                        new
                        {
                            WatchHistoryId = "W003",
                            BgPic = "https://www.niusnews.com/upload/imgs/default/2019MayJenny/24cute/1.jpg",
                            ComicId = "C003",
                            ComicPicId = "CP03",
                            EpId = "Ep03",
                            MemberId = "M003",
                            PeoplePic = "https://www.niusnews.com/upload/imgs/default/2019MayJenny/24cute/1.jpg"
                        },
                        new
                        {
                            WatchHistoryId = "W004",
                            BgPic = "https://www.niusnews.com/upload/imgs/default/2019MayJenny/24cute/1.jpg",
                            ComicId = "C004",
                            ComicPicId = "CP04",
                            EpId = "Ep04",
                            MemberId = "M004",
                            PeoplePic = "https://www.niusnews.com/upload/imgs/default/2019MayJenny/24cute/1.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
