// <auto-generated />
using BSWeBtoon.Front.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BSWeBtoon.Front.Migrations
{
    [DbContext(typeof(BSWebtoonDBContext))]
    [Migration("20220617143006_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BSWeBtoon.Front.Models.ComicCheckType", b =>
                {
                    b.Property<string>("ComicCheckTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ComicCheckTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComicCheckTypeId");

                    b.ToTable("ComicCheckTypes");

                    b.HasData(
                        new
                        {
                            ComicCheckTypeId = "1",
                            ComicCheckTypeName = "審核過"
                        },
                        new
                        {
                            ComicCheckTypeId = "2",
                            ComicCheckTypeName = "審核中"
                        },
                        new
                        {
                            ComicCheckTypeId = "3",
                            ComicCheckTypeName = "未審核"
                        },
                        new
                        {
                            ComicCheckTypeId = "4",
                            ComicCheckTypeName = "買版權"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
