// <auto-generated />
using BSWeBtoon.Front.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BSWeBtoon.Front.Migrations
{
    [DbContext(typeof(MemberLoginContext))]
    [Migration("20220617123046_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BSWeBtoon.Front.Models.Member", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CoinQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Login")
                        .HasColumnType("int");

                    b.Property<string>("MemberName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("setting")
                        .HasColumnType("bit");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = "A001",
                            CoinQuantity = 200,
                            Login = 1,
                            MemberName = "凍豆腐",
                            setting = true
                        },
                        new
                        {
                            MemberId = "A002",
                            CoinQuantity = 0,
                            Login = 2,
                            MemberName = "大阪燒",
                            setting = true
                        },
                        new
                        {
                            MemberId = "A003",
                            CoinQuantity = 500,
                            Login = 3,
                            MemberName = "鹽水雞",
                            setting = true
                        },
                        new
                        {
                            MemberId = "A004",
                            CoinQuantity = 1000,
                            Login = 4,
                            MemberName = "我愛的cp都是真的!",
                            setting = true
                        },
                        new
                        {
                            MemberId = "A005",
                            CoinQuantity = 300,
                            Login = 1,
                            MemberName = "一日顏狗，終生顏狗",
                            setting = true
                        },
                        new
                        {
                            MemberId = "A006",
                            CoinQuantity = 400,
                            Login = 2,
                            MemberName = "叫我大美女",
                            setting = true
                        },
                        new
                        {
                            MemberId = "A007",
                            CoinQuantity = 100,
                            Login = 3,
                            MemberName = "最帥就是我",
                            setting = true
                        },
                        new
                        {
                            MemberId = "A008",
                            CoinQuantity = 600,
                            Login = 4,
                            MemberName = "天下王者無雙",
                            setting = true
                        },
                        new
                        {
                            MemberId = "A009",
                            CoinQuantity = 700,
                            Login = 1,
                            MemberName = "迪特里是我ㄉ小可愛",
                            setting = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
